---
author:
  - 'Roman F. <romanf@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: makedbic
no_index:
  directory:
    - inc
    - t
requires:
  Config::Find: 0.26
  Config::General: 2.49
  ExtUtils::ModuleMaker: 0.51
  ExtUtils::ModuleMaker::TT: 0.93
  Getopt::Long::Descriptive: 0.086
  Path::Class: 0.21
  Test::DBIx::Class: 0
  Test::More: 0.42
  perl: 5.8.0
  version: 0.77
resources:
  license: http://dev.perl.org/licenses/
version: 0.1.2
